import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, signInWithCustomToken } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";

const telegram = window.Telegram.WebApp;
telegram.ready(); telegram.expand();
const language = (telegram.initDataUnsafe?.user?.language_code || navigator.language || "en").toLowerCase().startsWith("ru") ? "ru" : "en";
const tr = (ru, en) => language === "ru" ? ru : en;
const runtime = await (await fetch("/runtime-config.json", {cache: "no-store"})).json();
const api = runtime.apiBase || "";
let token = ""; let feedItems = []; let marketItems = []; let favoriteIds = new Set(); let isAdmin = false;
const labels = {deals:tr("Главная","Home"),market:tr("Рынок","Market"),search:tr("Подбор","Search"),saved:tr("Избранное","Saved"),settings:tr("Настройки","Settings"),admin:tr("Управление","Admin")};
document.querySelector("#subtitle").textContent = tr("Проверенные автомобили с расчётом", "Verified cars with financial analysis");

async function authorized(path, options = {}) {
  const response = await fetch(api + path, {...options, headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});
  if (!response.ok) throw new Error(`${response.status}: ${await response.text()}`);
  return response.json();
}
const money = value => value == null ? "—" : `${Number(value).toLocaleString(language === "ru" ? "ru-RU" : "en-US")} AED`;
function show(view) {
  document.querySelectorAll(".view").forEach(node => node.hidden = node.id !== `${view}-view`);
  document.querySelectorAll("#tabs button").forEach(node => node.classList.toggle("active", node.dataset.view === view));
  if(view==="market")renderMarket(); if(view==="search")loadSearches(); if(view==="saved")renderSaved(); if(view==="settings")loadSettings(); if(view==="admin")renderAdmin();
}
function buildTabs() {
  const tabs=document.querySelector("#tabs"); tabs.innerHTML="";
  for(const view of ["deals","market","search","saved","settings",...(isAdmin?["admin"]:[])]){const button=document.createElement("button");button.textContent=labels[view];button.dataset.view=view;button.onclick=()=>show(view);tabs.append(button);}
  tabs.hidden=false; show("deals");
}
async function toggleFavorite(item,button){const id=`${item.listing.source}:${item.listing.source_listing_id}`;const favorite=!favoriteIds.has(id);await authorized("/tma/favorites",{method:"POST",body:JSON.stringify({listing_id:id,favorite})});favorite?favoriteIds.add(id):favoriteIds.delete(id);button.textContent=favorite?tr("★ Сохранено","★ Saved"):tr("☆ Сохранить","☆ Save");}
function dealCard(item){const {listing,decision}=item;const card=document.createElement("article");card.className="card";const title=document.createElement("h2");title.textContent=listing.title;const meta=document.createElement("div");meta.className="deal-meta";meta.textContent=`${tr("Цена","Price")}: ${money(listing.price_aed)}\n${tr("Решение","Decision")}: ${decision.action}\n${tr("Ожидаемая прибыль","Expected profit")}: ${money(decision.expected_profit_aed)}\nROI: ${decision.roi_percent??"—"}%`;meta.style.whiteSpace="pre-line";const actions=document.createElement("div");actions.className="actions";const link=document.createElement("a");link.className="button";link.href=listing.url;link.target="_blank";link.rel="noopener";link.textContent=tr("Открыть объявление","Open listing");const favorite=document.createElement("button");favorite.className="secondary";const id=`${listing.source}:${listing.source_listing_id}`;favorite.textContent=favoriteIds.has(id)?tr("★ Сохранено","★ Saved"):tr("☆ Сохранить","☆ Save");favorite.onclick=()=>toggleFavorite(item,favorite);actions.append(link,favorite);card.append(title,meta,actions);return card;}
function renderDeals(){const root=document.querySelector("#feed");root.innerHTML="";if(!feedItems.length)root.innerHTML=`<div class="card"><b>${tr("Сейчас нет автомобилей, которые одновременно проходят требования по прибыли и риску.","No cars currently pass both profit and risk requirements.")}</b><p class="muted">${tr("Это не ошибка: неподтверждённые и убыточные варианты не выдаются за сделки. Создайте подбор — бот сообщит о новом совпадении.","This is not an error: unverified and unprofitable cars are not presented as deals. Create a search and the bot will notify you about a new match.")}</p></div>`;feedItems.forEach(item=>root.append(dealCard(item)));}
function renderMarket(){const root=document.querySelector("#market");root.innerHTML="";if(!marketItems.length)root.innerHTML=`<div class="card">${tr("Пока недостаточно автомобилей с подтверждёнными аналогами.","Not enough cars have verified comparables yet.")}</div>`;for(const item of marketItems){const card=dealCard(item);const warning=document.createElement("p");warning.className="muted";warning.textContent=tr("Рыночный объект для сравнения — не инвестиционная рекомендация.","Market reference — not an investment recommendation.");card.insertBefore(warning,card.querySelector(".actions"));root.append(card);}}
function renderSummary(data){const root=document.querySelector("#overview");root.innerHTML="";for(const [value,ru,en] of [[data.listings,"Автомобилей","Cars"],[data.analyzed,"Проанализировано","Analyzed"],[data.verified_market,"С аналогами","With comparables"],[data.deals,"Сделок","Deals"],[`${data.sources_enabled}/${data.sources}`,"Источников","Sources"]]){const node=document.createElement("div");node.className="stat";node.innerHTML=`<b>${value}</b><span>${tr(ru,en)}</span>`;root.append(node);}}
function renderSaved(){const root=document.querySelector("#saved");root.innerHTML="";const items=feedItems.filter(item=>favoriteIds.has(`${item.listing.source}:${item.listing.source_listing_id}`));if(!items.length)root.innerHTML=`<div class="card">${tr("Избранное пока пусто.","No saved cars yet.")}</div>`;items.forEach(item=>root.append(dealCard(item)));}
async function loadSearches(){const data=await authorized("/tma/searches");const root=document.querySelector("#searches");root.innerHTML="";for(const item of data.items){const row=document.createElement("div");row.className="card source-row";const text=document.createElement("div");text.textContent=item.query_text;const button=document.createElement("button");button.className="secondary";button.textContent=item.enabled?tr("Остановить","Pause"):tr("Включить","Enable");button.onclick=async()=>{await authorized(`/tma/searches/${item.search_id}`,{method:"POST",body:JSON.stringify({enabled:!item.enabled})});await loadSearches();};row.append(text,button);root.append(row);}}
async function loadSettings(){const data=await authorized("/tma/settings");document.querySelector("#budget").value=data.max_budget_aed??"";document.querySelector("#profit").value=data.min_profit_aed;document.querySelector("#roi").value=data.min_roi_percent;document.querySelector("#makes").value=(data.makes||[]).join(", ");document.querySelector("#min-year").value=data.min_year??"";document.querySelector("#max-year").value=data.max_year??"";document.querySelector("#mileage").value=data.max_mileage_km??"";}
async function renderAdmin(){if(!isAdmin)return;const data=await authorized("/admin/overview");document.querySelector("#admin-summary").textContent=tr(`Объявлений: ${data.snapshot_count}. Доставка: ${data.delivery_enabled?"включена":"выключена"}.`,`Listings: ${data.snapshot_count}. Delivery: ${data.delivery_enabled?"enabled":"disabled"}.`);const root=document.querySelector("#admin-sources");root.innerHTML="";for(const [name,enabled] of Object.entries(data.source_switches)){const row=document.createElement("div");row.className="card source-row";const state=document.createElement("div");state.innerHTML=`<b>${name}</b><br><span class="muted">${enabled?tr("Включён","Enabled"):tr("Выключен","Disabled")}</span>`;const button=document.createElement("button");button.textContent=enabled?tr("Выключить","Disable"):tr("Включить","Enable");button.onclick=async()=>{await authorized(`/admin/sources/${name}`,{method:"POST",body:JSON.stringify({enabled:!enabled})});await renderAdmin();};row.append(state,button);root.append(row);}}

document.querySelector("#search-title").textContent=tr("Подобрать автомобиль","Find a car");document.querySelector("#search-help").textContent=tr("Напишите обычным текстом: марка, бюджет, годы, пробег, GCC, прибыль и ROI.","Describe make, budget, years, mileage, GCC, profit and ROI.");document.querySelector("#create-search").textContent=tr("Создать подбор","Create search");
document.querySelector("#home-title").textContent=tr("Что сделать сейчас","What would you like to do?");document.querySelector("#home-text").textContent=tr("Создайте персональный подбор или изучите проверенные рыночные объекты. Инвестиционные сигналы появляются только после проверки цены, аналогов, расходов и риска.","Create a personal search or browse verified market references. Investment signals appear only after price, comparable, cost and risk checks.");document.querySelector("#home-search").textContent=tr("Подобрать машину","Find a car");document.querySelector("#home-market").textContent=tr("Смотреть рынок","Browse market");document.querySelector("#refresh-data").textContent=tr("Обновить","Refresh");document.querySelector("#deals-title").textContent=tr("Инвестиционные сделки","Investment deals");document.querySelector("#market-title").textContent=tr("Проверенный рынок","Verified market");document.querySelector("#market-help").textContent=tr("Автомобили с подтверждённой фиксированной ценой и достаточным числом аналогов. Они показаны для ориентира и не обязательно выгодны для перепродажи.","Cars with a verified fixed price and enough comparables. They are market references and are not necessarily profitable for resale.");document.querySelector("#home-search").onclick=()=>show("search");document.querySelector("#home-market").onclick=()=>show("market");document.querySelector("#refresh-data").onclick=()=>window.location.reload();
document.querySelector("#create-search").onclick=async()=>{const query=document.querySelector("#search-query").value.trim();if(!query)return;await authorized("/tma/searches",{method:"POST",body:JSON.stringify({query})});document.querySelector("#search-result").textContent=tr("Подбор включён. Бот сообщит о совпадениях.","Search enabled. The bot will notify you about matches.");document.querySelector("#search-query").value="";await loadSearches();};
for(const [id,ru,en] of [["budget-label","Максимальный бюджет, AED","Maximum budget, AED"],["profit-label","Минимальная прибыль, AED","Minimum profit, AED"],["roi-label","Минимальный ROI, %","Minimum ROI, %"],["makes-label","Марки через запятую","Makes, comma separated"],["years-label","Годы выпуска: от / до","Model years: from / to"],["mileage-label","Максимальный пробег, км","Maximum mileage, km"]])document.querySelector(`#${id}`).textContent=tr(ru,en);
document.querySelector("#save-settings").textContent=tr("Сохранить настройки","Save settings");document.querySelector("#admin-title").textContent=tr("Управление проектом","Project control");
document.querySelector("#settings-form").onsubmit=async event=>{event.preventDefault();const number=id=>document.querySelector(id).value?Number(document.querySelector(id).value):null;await authorized("/tma/settings",{method:"POST",body:JSON.stringify({max_budget_aed:number("#budget"),min_profit_aed:number("#profit")||0,min_roi_percent:number("#roi")||0,makes:document.querySelector("#makes").value.split(",").map(x=>x.trim()).filter(Boolean),models:[],min_year:number("#min-year"),max_year:number("#max-year"),max_mileage_km:number("#mileage"),specifications:[],body_types:[]})});document.querySelector("#settings-result").textContent=tr("Сохранено","Saved");const data=await authorized("/tma/feed");feedItems=data.items;renderDeals();};

try{const config=await(await fetch("/__/firebase/init.json")).json();const auth=getAuth(initializeApp(config));const exchange=await fetch(api+"/tma/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({init_data:telegram.initData})});if(!exchange.ok)throw new Error(await exchange.text());const custom=await exchange.json();const credential=await signInWithCustomToken(auth,custom.firebase_custom_token);token=await credential.user.getIdToken();const [feed,favorites,summary,market]=await Promise.all([authorized("/tma/feed"),authorized("/tma/favorites"),authorized("/tma/summary"),authorized("/tma/market-watch")]);feedItems=feed.items;marketItems=market.items;favoriteIds=new Set(favorites.items);isAdmin=feed.is_admin;document.querySelector("#state").textContent=tr(`Рынок обновлён · инвестиционных сделок: ${feedItems.length}`,`Market updated · investment deals: ${feedItems.length}`);document.querySelector("#connection").textContent=tr("Онлайн","Online");renderSummary(summary);renderDeals();buildTabs();}catch(error){document.querySelector("#state").textContent=tr("Не удалось подключиться","Connection failed");document.querySelector("#connection").textContent=tr("Ошибка","Error");document.querySelector("#error").textContent=error.message;}
